// <auto-generated />
namespace movie_store.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class GetDataFromAPI : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GetDataFromAPI));
        
        string IMigrationMetadata.Id
        {
            get { return "202105110830041_GetDataFromAPI"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
